// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnrsqiinquoeeismvnua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucnNxaWlucXVvZWVpc212bnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTQ5MDAsImV4cCI6MjA2NjY3MDkwMH0.hlqEJW1TUaxUvRiG2HLeMXv34zrgsyTzmhU6sHeiM-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);