
name: Daily Supabase Reminder

on:
  schedule:
    - cron: '0 5 * * *' # 5:00 UTC = 10:30 AM IST
  workflow_dispatch:

jobs:
  call-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Schedule Reminder Check Function
        run: |
          echo "Calling schedule-reminder-check function at $(date)"
          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST "https://mnrsqiinquoeeismvnua.supabase.co/functions/v1/schedule-reminder-check" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"source": "github-cron", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}')
          
          http_status=$(echo "$response" | grep "HTTP_STATUS" | cut -d: -f2)
          response_body=$(echo "$response" | sed '/HTTP_STATUS/d')
          
          echo "Response Status: $http_status"
          echo "Response Body: $response_body"
          
          if [ "$http_status" -ne 200 ]; then
            echo "Error: Function call failed with status $http_status"
            exit 1
          fi
          
          echo "Cron job completed successfully"
